config/routes.rb
Rails.application.routes.draw do
  get 'product_imports/new'
  get 'product_imports/create'
  get 'menus/index'
  get 'menu_permissions/index'
  get 'siswas/index'
  get 'rombels/index'
  get 'jurusans/index'
  get 'rayons/index'

  resources :menus
  resources :menu_permissions
  resources :rombels
  resources :jurusans
  resources :rayons

  # Login
  devise_for :users

  # Datatables
  get 'get_dataset', to: 'pages#get_dataset'

  # config/routes.rb
  resources :siswas do
    collection { post :import }
  end

  root 'menus#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rayon.rb
class Rayon < ApplicationRecord
    # validate :rombel, presence: true
    validates_presence_of :rayon
    has_many :siswas, dependent: :delete_all
end

app/controllers/rayons_controller.rb
class RayonsController < ApplicationController
  before_action :set_rayon, only: [:show, :edit, :update, :destroy]

  # GET /rayons
  # GET /rayons.json
  def index
    @rayons = Rayon.all
  end

  # GET /rayons/1
  # GET /rayons/1.json
  def show
  end

  # GET /rayons/new
  def new
    @rayon = Rayon.new
  end

  # GET /rayons/1/edit
  def edit
  end

  # POST /rayons
  # POST /rayons.json
  def create
    @rayon = Rayon.new(rayon_params)

    respond_to do |format|
      if @rayon.save
        format.html { redirect_to @rayon, notice: 'Rayon was successfully created.' }
        format.json { render :show, status: :created, location: @rayon }
      else
        format.html { render :new }
        format.json { render json: @rayon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rayons/1
  # PATCH/PUT /rayons/1.json
  def update
    respond_to do |format|
      if @rayon.update(rayon_params)
        format.html { redirect_to @rayon, notice: 'Rayon was successfully updated.' }
        format.json { render :show, status: :ok, location: @rayon }
      else
        format.html { render :edit }
        format.json { render json: @rayon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rayons/1
  # DELETE /rayons/1.json
  def destroy
    @rayon.destroy
    respond_to do |format|
      format.html { redirect_to rayons_url, notice: 'Rayon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rayon
      @rayon = Rayon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rayon_params
      params.require(:rayon).permit(:rayon)
    end
end

app/helpers/rayons_helper.rb
module RayonsHelper
end

app/views/rayons/_form.html.erb
<%= form_with(model: rayon, local: true) do |form| %>
  <% if rayon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rayon.errors.count, "error") %> prohibited this rayon from being saved:</h2>

      <ul>
        <% rayon.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rayon %>
    <%= form.text_field :rayon %>
  </div>

  <div class="actions" align="center">
    <%= form.submit %>
  </div>
<% end %>

app/views/rayons/edit.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>Editing Rayon</h1>
    </div>
    
    <div class="card-body">
      <%= render 'form', rayon: @rayon %>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Show', @rayon, class: 'btn btn-outline-info' %>
      <%= link_to 'Back', rayons_path, class: 'btn btn-outline-secondary' %>
    <div>

  </div>
</div>

app/views/rayons/index.html.erb
<p id="notice"><%= notice %></p>
<title>Data Rayon</title>
<div class="container">
  <div class="card">
    <div class="row-3">
      <div class="card-header" align="center">
        <h1 align="center">Rayon</h1>
      </div>
    </div>
    <div class="card-body">
      <div class="col-md-12">
        <div class="container">
          <div class="row">
            <div class="col">
              <%= link_to 'New Rayon', new_rayon_path, class: 'btn btn-primary' %>
            </div>
          <div class="col">
          </div>
        </div>  
      </div>
    </div>
    <br>
      <table class="table table-bordered table-striped table-hover table-condensed table-sm">
      <caption>Table Rayon</caption>
        <thead align="center" class="table-dark">
          <tr>
            <th>Rayon</th>
            <th colspan="3">Aksi</th>
          </tr>
        </thead>
        <tbody align="center">
          <% @rayons.each do |rayon| %>
            <tr>
              <td><%= rayon.rayon.capitalize %></td>
              <td align="center" width="10%"><%= link_to 'Show', rayon, class: 'btn btn-info' %></td>
              <td align="center" width="10%"><%= link_to 'Edit', edit_rayon_path(rayon), class: 'btn btn-warning' %></td>
              <td align="center" width="10%"><%= link_to 'Destroy', rayon, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

      <br>

app/views/rayons/new.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>New Rayon</h1>
    </div>

    <div class="card-body">      
      <%= render 'form', rayon: @rayon %>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Back', rayons_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>

app/views/rayons/show.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>Show Rayon</h1>
    </div>

    <div class="card-body">
      <p>
        <strong>Rayon:</strong>
        <%= @rayon.rayon %>
      </p>
    </div>
    
    <div class="card-footer" align="center">
      <%= link_to 'Edit', edit_rayon_path(@rayon), class: 'btn btn-outline-warning' %>
      <%= link_to 'Back', rayons_path, class: 'btn btn-outline-secondary' %>
    </div>

  </div>
</div>