config/routes.rb
Rails.application.routes.draw do
  get 'product_imports/new'
  get 'product_imports/create'
  get 'menus/index'
  get 'menu_permissions/index'
  get 'siswas/index'
  get 'rombels/index'
  get 'jurusans/index'
  get 'rayons/index'

  resources :menus
  resources :menu_permissions
  resources :rombels
  resources :jurusans
  resources :rayons

  # Login
  devise_for :users

  # Datatables
  get 'get_dataset', to: 'pages#get_dataset'

  # config/routes.rb
  resources :siswas do
    collection { post :import }
  end

  root 'menus#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/siswa.rb
class Siswa < ApplicationRecord
  belongs_to :rombel
  belongs_to :rayon
  # validates :nama, :jk, presence: true
  validates_presence_of :nama, :jk

  # Generate a CSV File of All Movie Records
  def self.to_csv(fields = column_names, options={})
    CSV.generate(options) do |csv|
      csv << fields
      all.each do |siswa|
        csv << siswa.attributes.values_at(*fields)
      end
    end
  end

  # Import CSV, Find or Create Movie by its title.
  # Update the record.
  # def self.import(file)
  #   CSV.foreach(file.path, headers: true) do |row|
  #     movies_hash = row.to_hash
  #     movie = find_or_create_by!(nama: siswas_hash[‘nama’])
  #     movie.update_attributes(movies_hash)
  #   end
  # end


# Rails Casts
# def self.to_csv(options = {})
#   CSV.generate(options) do |csv|
#     csv << column_names
#     all.each do |siswa|
#       csv << siswa.attributes.values_at(*column_names)
#     end
#   end
# end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Siswa.create! row.to_hash
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      siswa = find_by_id(row["id"]) || new
      siswa.attributes = row.to_hash.slice(*accessible_attributes)
      siswa.save!
    end
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      siswa = find_by_id(row["id"]) || new
      siswa.attributes = row.to_hash.slice(*accessible_attributes)
      siswa.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when '.csv' then Csv.new(file.path, nil, :ignore)
    when '.xls' then Excel.new(file.path, nil, :ignore)
    when '.xlsx' then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end





end

app/controllers/siswas_controller.rb
class SiswasController < ApplicationController
  before_action :set_siswa, only: [:show, :edit, :update, :destroy]

  # GET /siswas
  # GET /siswas.json
  def index
    @siswas = Siswa.order(:nama)
    respond_to do |format|
      format.html
      format.csv { send_data @siswas.to_csv(['nama', 'jk', 'rombel_id', 'rayon_id']).titleize }
      format.xls { send_data @siswas.to_csv(col_sep: "\t") }
    end
  end

  def import
    Siswa.import(params[:file])
    redirect_to root_url, notice: "Siswa Uploaded successfully"
  end

  # GET /siswas/1
  # GET /siswas/1.json
  def show
  end

  # GET /siswas/new
  def new
    @siswa = Siswa.new
  end

  # GET /siswas/1/edit
  def edit
  end


  # POST /siswas
  # POST /siswas.json
  def create
    @siswa = Siswa.new(siswa_params)

    respond_to do |format|
      if @siswa.save
        format.html { redirect_to @siswa, notice: 'Siswa was successfully created.' }
        format.json { render :show, status: :created, location: @siswa }
      else
        format.html { render :new }
        format.json { render json: @siswa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /siswas/1
  # PATCH/PUT /siswas/1.json
  def update
    respond_to do |format|
      if @siswa.update(siswa_params)
        format.html { redirect_to @siswa, notice: 'Siswa was successfully updated.' }
        format.json { render :show, status: :ok, location: @siswa }
      else
        format.html { render :edit }
        format.json { render json: @siswa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /siswas/1
  # DELETE /siswas/1.json
  def destroy
    @siswa.destroy
    respond_to do |format|
      format.html { redirect_to siswas_url, notice: 'Siswa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_siswa
      @siswa = Siswa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def siswa_params
      params.require(:siswa).permit(:nama, :jk, :rombel_id, :rayon_id)
    end
end

app/helpers/siswas_helper.rb
module SiswasHelper
end

app/views/siswas/_form.html.erb
<%= form_with(model: siswa, local: true) do |form| %>
  <% if siswa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(siswa.errors.count, "error") %> prohibited this siswa from being saved:</h2>

      <ul>
        <% siswa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :nama %>
    <%= form.text_field :nama, size: '22' %>
  </div>

  <div class="form-group">
    <%= form.label :Jenis_Kelamin %>
    <%= form.radio_button :jk, 'Laki-laki' %>
    <%= form.label :jk, "Laki-Laki", :value => "Laki-laki"  %>
    <%= form.radio_button :jk, 'Perempuan' %>
    <%= form.label :jk, "Perempuan", :value => "Perempuan" %>
  </div>

  <div class="form-group">
    <%= form.label :rombel_id %>
    <%= form.select(:rombel_id, Rombel.all.map {|r| [r.rombel, r.id]}, :prompt => "Pilih Rombel") %>
  </div>
  
  <div class="form-group">
    <%= form.label :rayon_id %>
    <%= form.select(:rayon_id, Rayon.all.map {|r| [r.rayon, r.id]}, :prompt => "Pilih Rayon") %>
  </div>

  <div class="actions" align="center">
    <%= form.submit %>
  </div>
<% end %>

app/views/siswas/edit.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>Editing Siswa</h1>
    </div>

    <div class="card-body">
      <%= render 'form', siswa: @siswa %>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Show', @siswa, class: 'btn btn-outline-info' %>
      <%= link_to 'Back', siswas_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>

app/views/siswas/index.html.erb
<p id="notice"><%= notice %></p>
<p>
  Download:
  <%= link_to "CSV", siswas_path(format: "csv") %> |
  <%= link_to "Excel", siswas_path(format: "xls") %>
</p>

<h2>Import Students</h2>
<%= form_tag import_siswas_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<br>
<title>Data Siswa</title>
<div class="container">
  <div class="card">
      <div class="card-header">
        <h1 align="center">Siswa</h1>
      </div>
      <div class="card-body">
        <div class="col-md-12">
          <div class="container">
            <%= link_to 'New Siswa', new_siswa_path, class: 'btn btn-primary' %> 
          </div>
        </div>
      <br>
      <table id="example" class="table table-striped table-bordered table-hover table-condensed table-sm">
        <caption>Table Siswa</caption>
          <thead align="center" class="table-dark">
            <tr>
              <th>Nama</th>
              <th>Jenis Kelamin</th>
              <th>Rombel</th>
              <th>Rayon</th>
              <th>Aksi</th>
            </tr>
          </thead>
          <tbody align="center" id="static-table">
          <% @siswas.each do |siswa| %> 
          <tr>
            <td><%= siswa.nama.titleize %></td>
            <td><%= siswa.jk %></td>
            <td><%= siswa.rombel.jurusan.jurusan %> <%= siswa.rombel.rombel %></td>
            <td><%= siswa.rayon.rayon.capitalize %></td>
            <td>
              <%= link_to 'Show', siswa, class:"btn btn-info" %>
              <%= link_to 'Edit', edit_siswa_path(siswa), class:"btn btn-warning" %>
              <%= link_to 'Destroy', siswa, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger "%>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready( function () {
    $('#example').DataTable();
  } );
</script>

app/views/siswas/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Nama</Data></Cell>
        <Cell><Data ss:Type="String">Jenis Kelamin</Data></Cell>
        <Cell><Data ss:Type="String">Jurusan</Data></Cell>
        <Cell><Data ss:Type="String">Rombel</Data></Cell>
        <Cell><Data ss:Type="String">Rayon</Data></Cell>
      </Row>
    <% @siswas.each do |siswa| %>
      <Row>
        <Cell><Data ss:Type="String"><%= siswa.nama %></Data></Cell>
        <Cell><Data ss:Type="String"><%= siswa.jk %></Data></Cell>
        <Cell><Data ss:Type="String"><%= siswa.rombel.jurusan.jurusan %></Data></Cell
        <Cell><Data ss:Type="String"><%= siswa.rombel.rombel %></Data></Cell>
        <Cell><Data ss:Type="String"><%= siswa.rayon.rayon %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/siswas/new.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>New Siswa</h1>
    </div>

    <div class="card-body">
      <%= render 'form', siswa: @siswa %>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Back', siswas_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>

app/views/siswas/show.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1 align="center">Show Siswa</h1>
    </div>
    <div class="card-body">
        <p>
          <strong>Nama:</strong>
          <%= @siswa.nama %>
        </p>
        <p>
          <strong>Jenis Kelamin:</strong>
          <%= @siswa.jk %>
        </p>
        <p>
          <strong>Rombel:</strong>
          <%= @siswa.rombel.jurusan.jurusan %> <%= @siswa.rombel.rombel %>
        </p>
        <p>
          <strong>Rayon:</strong>
          <%= @siswa.rayon.rayon %>
        </p>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Edit', edit_siswa_path(@siswa), class: 'btn btn-outline-warning' %>
      <%= link_to 'Back', siswas_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>