config/routes.rb
Rails.application.routes.draw do
  get 'product_imports/new'
  get 'product_imports/create'
  get 'menus/index'
  get 'menu_permissions/index'
  get 'siswas/index'
  get 'rombels/index'
  get 'jurusans/index'
  get 'rayons/index'

  resources :menus
  resources :menu_permissions
  resources :rombels
  resources :jurusans
  resources :rayons

  # Login
  devise_for :users

  # Datatables
  get 'get_dataset', to: 'pages#get_dataset'

  # config/routes.rb
  resources :siswas do
    collection { post :import }
  end

  root 'menus#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rombel.rb
class Rombel < ApplicationRecord
  belongs_to :jurusan
  # validates :rombel, presence: true
  validates_presence_of :rombel
  has_many :siswas, dependent: :delete_all
end

app/controllers/rombels_controller.rb
class RombelsController < ApplicationController
  before_action :set_rombel, only: [:show, :edit, :update, :destroy]

  # GET /rombels
  # GET /rombels.json
  def index
    @rombels = Rombel.all
  end

  # GET /rombels/1
  # GET /rombels/1.json
  def show
  end

  # GET /rombels/new
  def new
    @rombel = Rombel.new
  end

  # GET /rombels/1/edit
  def edit
  end

  # POST /rombels
  # POST /rombels.json
  def create
    @rombel = Rombel.new(rombel_params)

    respond_to do |format|
      if @rombel.save
        format.html { redirect_to @rombel, notice: 'Rombel was successfully created.' }
        format.json { render :show, status: :created, location: @rombel }
      else
        format.html { render :new }
        format.json { render json: @rombel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rombels/1
  # PATCH/PUT /rombels/1.json
  def update
    respond_to do |format|
      if @rombel.update(rombel_params)
        format.html { redirect_to @rombel, notice: 'Rombel was successfully updated.' }
        format.json { render :show, status: :ok, location: @rombel }
      else
        format.html { render :edit }
        format.json { render json: @rombel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rombels/1
  # DELETE /rombels/1.json
  def destroy
    @rombel.destroy
    respond_to do |format|
      format.html { redirect_to rombels_url, notice: 'Rombel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rombel
      @rombel = Rombel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rombel_params
      params.require(:rombel).permit(:jurusan_id, :rombel)
    end
end

app/helpers/rombels_helper.rb
module RombelsHelper
end

app/views/rombels/_form.html.erb
<%= form_with(model: rombel, local: true) do |form| %>
  <% if rombel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rombel.errors.count, "error") %> prohibited this rombel from being saved:</h2>

      <ul>
        <% rombel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :jurusan_id %>
    <%= form.select(:jurusan_id, Jurusan.all.map {|j| [j.jurusan, j.id]}, :prompt => "Pilih Jurusan") %>
  </div>

  <div class="field">
    <%= form.label :rombel %>
    <%= form.text_field :rombel %>
  </div>

  <div class="actions" align="center">
    <%= form.submit %>
  </div>
<% end %>

app/views/rombels/edit.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>Editing Rombel</h1>
    </div>

    <div class="card-body">
      <%= render 'form', rombel: @rombel %>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Show', @rombel, class: 'btn btn-outline-info' %>
      <%= link_to 'Back', rombels_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>  

app/views/rombels/index.html.erb
<p id="notice"><%= notice %></p>
<title>Data Rombel</title>
<div class="container">
  <div class="card">
    <div class="row-3">
      <div class="card-header" align="center">
        <h1 align="center">Rombel</h1>
      </div>
    </div>
    <div class="card-body">
      <div class="col-md-12">
        <div class="container">
          <div class="row">
            <div class="col">
              <%= link_to 'New Rombel', new_rombel_path, class: 'btn btn-primary' %>
            </div>
          <div class="col">
          </div>
        </div>  
      </div>
    </div>
    <br>
      <table class="table table-bordered table-striped table-hover table-condensed table-sm">
      <caption>Table Rombel</caption>
        <thead align="center" class="table-dark">
          <tr>
            <th>Jurusan</th>
            <th>Rombel</th>
            <th colspan="3">Aksi</th>
          </tr>
        </thead>
        <tbody align="center">
        <% @rombels.each do |rombel| %>
          <tr>
            <td><%= rombel.jurusan.jurusan.upcase %></td>
            <td><%= rombel.rombel.upcase %></td>
            <td align="center" width="10%"><%= link_to 'Show', rombel, class: 'btn btn-info' %></td>
            <td align="center" width="10%"><%= link_to 'Edit', edit_rombel_path(rombel), class:'btn btn-warning' %></td>
            <td align="center" width="10%"><%= link_to 'Destroy', rombel, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<br>

app/views/rombels/new.html.erb
<div class="container">
  <div class="card">

    <div class="card-header"  align="center">
      <h1>New Rombel</h1>
    </div>

    <div class="card-body">
      <%= render 'form', rombel: @rombel %>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Back', rombels_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>  

app/views/rombels/show.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>Show Rombel</h1>
    </div>

    <div class="card-body">
      <p>
        <strong>Jurusan:</strong>
        <%= @rombel.jurusan.jurusan %>
      </p>
      <p>
        <strong>Rombel:</strong>
        <%= @rombel.rombel %>
      </p>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Edit', edit_rombel_path(@rombel), class: 'btn btn-outline-warning' %>
      <%= link_to 'Back', rombels_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>