config/routes.rb
Rails.application.routes.draw do
  get 'product_imports/new'
  get 'product_imports/create'
  get 'menus/index'
  get 'menu_permissions/index'
  get 'siswas/index'
  get 'rombels/index'
  get 'jurusans/index'
  get 'rayons/index'

  resources :menus
  resources :menu_permissions
  resources :rombels
  resources :jurusans
  resources :rayons

  # Login
  devise_for :users

  # Datatables
  get 'get_dataset', to: 'pages#get_dataset'

  # config/routes.rb
  resources :siswas do
    collection { post :import }
  end

  root 'menus#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/jurusan.rb
class Jurusan < ApplicationRecord
    # validates :jurusan, presence: true
    validates_presence_of :jurusan
    has_many :rombels, dependent: :delete_all
end

app/controllers/jurusans_controller.rb
class JurusansController < ApplicationController
  before_action :set_jurusan, only: [:show, :edit, :update, :destroy]

  # GET /jurusans
  # GET /jurusans.json
  def index
    @jurusans = Jurusan.all
  end

  # GET /jurusans/1
  # GET /jurusans/1.json
  def show
  end

  # GET /jurusans/new
  def new
    @jurusan = Jurusan.new
  end

  # GET /jurusans/1/edit
  def edit
  end

  # POST /jurusans
  # POST /jurusans.json
  def create
    @jurusan = Jurusan.new(jurusan_params)

    respond_to do |format|
      if @jurusan.save
        format.html { redirect_to @jurusan, notice: 'Jurusan was successfully created.' }
        format.json { render :show, status: :created, location: @jurusan }
      else
        format.html { render :new }
        format.json { render json: @jurusan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jurusans/1
  # PATCH/PUT /jurusans/1.json
  def update
    respond_to do |format|
      if @jurusan.update(jurusan_params)
        format.html { redirect_to @jurusan, notice: 'Jurusan was successfully updated.' }
        format.json { render :show, status: :ok, location: @jurusan }
      else
        format.html { render :edit }
        format.json { render json: @jurusan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jurusans/1
  # DELETE /jurusans/1.json
  def destroy
    @jurusan.destroy
    respond_to do |format|
      format.html { redirect_to jurusans_url, notice: 'Jurusan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jurusan
      @jurusan = Jurusan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jurusan_params
      params.require(:jurusan).permit(:jurusan)
    end
end

app/helpers/jurusans_helper.rb
module JurusansHelper
end

app/views/jurusans/_form.html.erb
<%= form_with(model: jurusan, local: true) do |form| %>
  <% if jurusan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(jurusan.errors.count, "error") %> prohibited this jurusan from being saved:</h2>
      
      <ul>
        <% jurusan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :jurusan %>
    <%= form.text_field :jurusan %>
  </div>

  <div class="actions" align="center">
    <%= form.submit %>
  </div>
<% end %>

app/views/jurusans/edit.html.erb
<div class="container">
  <div class="card">

    <div class="card-header">
      <h1 align="center">Editing Jurusan</h1>
    </div>

    <div class="card-body">
      <%= render 'form', jurusan: @jurusan %>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Show', @jurusan, class: 'btn btn-outline-info' %>
      <%= link_to 'Back', jurusans_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>

app/views/jurusans/index.html.erb
<p id="notice"><%= notice %></p>
<title>Data Jurusan</title>
<div class="container">
  <div class="card">
    <div class="row-3">
      <div class="card-header" align="center">
        <h1 align="center">Jurusan</h1>
      </div>
    </div>
    <div class="card-body">
      <div class="col-md-12">
        <div class="container">
          <div class="row">
            <div class="col">
              <%= link_to 'New Jurusan', new_jurusan_path, class: 'btn btn-primary'%>
            </div>
          <div class="col">
        </div>
      </div>  
    </div>
  </div>
  <br> 
    <table class="table table-bordered table-striped table-hover table-condensed table-sm" align="center">
    <caption>Table Jurusan</caption>
      <thead align="center" class="table-dark">
        <tr>
          <th>Jurusan</th>
          <th colspan="3">Aksi</th>
        </tr>
      </thead>
      <tbody align="center">
        <% @jurusans.each do |jurusan| %>
          <tr>
            <td><%= jurusan.jurusan.upcase %></td>
            <td align="center" width="10%"><%= link_to 'Show', jurusan, class: 'btn btn-info' %></td>
            <td align="center" width="10%"><%= link_to 'Edit', edit_jurusan_path(jurusan), class: 'btn btn-warning' %></td>
            <td align="center" width="10%"><%= link_to 'Destroy', jurusan, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>
<br>

app/views/jurusans/new.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>New Jurusan</h1>
    </div>

    <div class="card-body">
      <%= render 'form', jurusan: @jurusan %>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Back', jurusans_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>

app/views/jurusans/show.html.erb
<div class="container">
  <div class="card">

    <div class="card-header" align="center">
      <h1>Show Siswa</h1>
    </div>

    <div class="card-body">
      <p>
        <strong>Jurusan:</strong>
        <%= @jurusan.jurusan %>
      </p>
    </div>

    <div class="card-footer" align="center">
      <%= link_to 'Edit', edit_jurusan_path(@jurusan), class: 'btn btn-outline-warning' %>
      <%= link_to 'Back', jurusans_path, class: 'btn btn-outline-secondary' %>
    </div>
    
  </div>
</div>